name: Run Python Script

on:
  schedule:
    - cron: '0 1 * * *'  # Run at 6:50 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script
        run: python titan.py
