name: Run Python Script

on:
  schedule:
    - cron: '03 6 * * *'  # Run at 6:55 AM UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: pip install -r .github/workflows/requirements.txt
      - name: Run Script
        run: python .github/workflows/titan.py
